version = 1

[[analyzers]]
name = "scala"

[[analyzers]]
name = "php"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "8"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/meetroop/multi"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "gofmt"